name: CI/CD

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

    # checkout
    - name: Checkout Repository
      uses: actions/checkout@v3

    # docker compose up
    - name: Start Docker Compose
      run: docker compose up -d

    # end to end testing
    - name: Run Tests
      run: bash ./app/e2e.sh
    
    # git tag
    - name: Tagger
      id: tagger
      run: |

        bash ./app/tagger.sh
        

    - name: test
      env: 
        NEW_TAG: ${{ steps.tagger.output.tagger.NEW_TAG }}
      run: echo ${{env.NEW_TAG}}
        
    # login to dockerhub    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # publish to dockerhub    
    - name: publish to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: |
        docker images
        docker tag portfolio-app:latest jack3131/electify:latest
        docker push jack3131/electify:latest

        docker tag portfolio-db:latest jack3131/mysql:latest
        docker push jack3131/mysql:latest


    # report
    - name: failure
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        message="âŒ CI for branch $GITHUB_REF_NAME failed ðŸš¨ðŸ’€
        Run number: $GITHUB_RUN_NUMBER"
        curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null

    - name: success
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        message="âœ… CI for branch $GITHUB_REF_NAME succeeded ðŸš€ðŸ¤˜
        Run number: $GITHUB_RUN_NUMBER"
        curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null