name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start Docker Compose
      run: docker compose up -david
      continue-on-error: true

    - name: Run Tests
      run: |
        bash ./app/e2e.sh
      continue-on-error: true

  notify-telegram:
    name: TelegramNotification
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
        
      - name: failure
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo $CI
          message="âŒ CI for branch $GITHUB_REF_NAME failed ðŸš¨ðŸ˜ž
          Run number: $GITHUB_RUN_NUMBER"
          curl -s \
          --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" \
          --data-urlencode "text=$message" \
          "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null

      - name: success
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo $CI
          message="âœ… CI for branch $GITHUB_REF_NAME succeeded ðŸš€ðŸ¤˜
          Run number: $GITHUB_RUN_NUMBER"
          curl -s \
          --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" \
          --data-urlencode "text=$message" \
          "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null